### ISSUE TITLE
How can i run test for diff version schemas?

### ISSUE THREAD

**Issue by kaioken** [as-yakovenko/laravel-lighthouse-graphql-multi-schema#2]
Thank you for the package. I have implemented it, but I am encountering an issue when attempting to run a test within the project (PHP artisan test). I cannot specify the version of my query that will be tested against.

Update: 
This is my solution let me know if you have a better approach 
https://github.com/bakaphp/kanvas-ecosystem-api/pull/2485/files#diff-abf1fa77a19f720052b75bc802df0260157b9064d8c3c12a80794f01e9acc065R36

**Comment by as-yakovenko** [comment]
Hi! Thank you for your question and for using the package.

The purpose of this package is to manage multiple GraphQL schemas and link them to separate routes. It doesn't directly focus on testing queries or mutations for specific schemas. However, you can achieve this functionality by dynamically setting the schema version during tests.

**Option 1: Using Environment Variables**

Run the test command with the schema specified as an environment variable:
```bash
GRAPHQL_SCHEMA=schema2 php artisan test
```
In your tests, read this variable:

```php
protected string $graphqlVersion;

protected function setUp(): void
{
    parent::setUp();
    $this->graphqlVersion = env('GRAPHQL_SCHEMA', 'schema1'); // Default to schema1
}
```

Update your route logic to use the selected schema:

```php
protected function graphQLEndpointUrl(array $routeParams = []): string
{
    $config = Container::getInstance()->make(ConfigRepository::class);

    $routeName = match ($this->graphqlVersion) {
        'schema1' => $config->get('lighthouse.multi_schemas.schema1.route_name'),
        'schema2' => $config->get('lighthouse.multi_schemas.schema2.route_name'),
        default => $config->get('lighthouse.route.name'),
    };

    return route($routeName, $routeParams);
}
```

**Option 2: Custom Artisan Command**

You can create a custom Artisan command to simplify the process:

```bash
php artisan test:schema schema2
```

The command will set the schema and run the tests:

```php
namespace App\Console\Commands;

use Illuminate\Console\Command;

class TestSchema extends Command
{
    protected $signature = 'test:schema {schema}';
    protected $description = 'Run tests for a specific GraphQL schema';

    public function handle()
    {
        $schema = $this->argument('schema');

        // Set the environment variable
        putenv("GRAPHQL_SCHEMA=$schema");

        // Run the tests
        $this->call('test');
    }
}
```


Let me know if this helps or if you have more questions!
